services:
  url_shortener_db:
    image: postgres:latest
    container_name: test_db
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
    volumes:
      - data_db:/var/lib/postgresql/data
    networks:
      - app_network

  url_shortener_cache:
    image: redis:latest
    container_name: test_cache
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${CACHE_PASSWORD}
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD --maxmemory 100mb --maxmemory-policy volatile-lru"
    ports:
      - ${CACHE_PORT}:6379
    volumes:
      - cache_data:/data
    networks:
      - app_network

  url_shortener_app:
    image: url_shortener_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data_app:/usr/src/app
    restart: unless-stopped
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - CACHE_PORT=${CACHE_PORT}
      - CACHE_PASSWORD=${CACHE_PASSWORD}
      - CACHE_HOST=${CACHE_HOST}
      - JWT_TOKEN_SECRET=${JWT_TOKEN_SECRET}
    depends_on:
      - url_shortener_cache
      - url_shortener_db
    networks:
      - app_network

volumes:
  data_db:
  data_app:
  cache_data:
    driver: local

networks:
  app_network:
